# Generated by Django 5.2 on 2025-06-09 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='logos_usuarios/')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos_usuarios/')),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Laptop', 'Laptop'), ('Smartphone', 'Smartphone'), ('Tablet', 'Tablet'), ('Otro', 'Otro')], max_length=20)),
                ('sistema_operativo', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('fecha_autorizacion', models.DateField()),
                ('logo', models.FileField(blank=True, null=True, upload_to='logos_dispositivos/')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos_dispositivos/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='Dispositivos.usuario')),
            ],
        ),
    ]
